[package]
name = "provider-tests"
edition.workspace = true
version.workspace = true
license.workspace = true
publish = false

[dependencies]
provider-common = { path = "../provider-common" }
anyhow = { workspace = true }
base64 = "0.22"
greentic-interfaces-wasmtime = { workspace = true }
serde_json = { workspace = true }
wasmtime = { version = "=41.0.2", features = ["component-model", "cache"] }
wasmtime-wasi = "=41.0.2"

[dev-dependencies]
serde = { workspace = true }
greentic-types = { workspace = true }
insta = { workspace = true }
hmac = { workspace = true }
sha2 = { workspace = true }
messaging-universal-dto = { workspace = true }
