[package]
name = "provider-tests"
edition.workspace = true
version.workspace = true
license.workspace = true
publish = false

[dependencies]
provider-common = { path = "../provider-common" }

[dev-dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
greentic-interfaces-wasmtime = { workspace = true }
greentic-types = { workspace = true }
anyhow = { workspace = true }
insta = { workspace = true }
wasmtime = { version = "40", features = ["component-model", "cache"] }
wasmtime-wasi = "40"
