[package]
name = "provider-tests"
edition.workspace = true
version.workspace = true
license.workspace = true
publish = false

[dependencies]
provider-common = { path = "../provider-common" }
anyhow = { workspace = true }
base64.workspace = true
greentic-interfaces-wasmtime = { workspace = true }
serde_json = { workspace = true }
wasmtime = { workspace = true }
wasmtime-wasi.workspace = true

[dev-dependencies]
serde = { workspace = true }
greentic-types = { workspace = true }
insta = { workspace = true }
hmac = { workspace = true }
sha2 = { workspace = true }
