[workspace]
members = [
    "crates/*",
    "components/*",
]
resolver = "2"

[workspace.package]
edition = "2024"
version = "0.4.5"
license = "MIT"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
thiserror = "2"
wit-bindgen = "0.49"
serde_json = "1"
hmac = "0.12"
sha2 = "0.10"
urlencoding = "2"
wasmtime = { version = "29", features = ["component-model"] }
