[package]
name = "provider-common"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
thiserror.workspace = true
serde_json.workspace = true
schemars = { workspace = true, optional = true }

[dev-dependencies]
anyhow.workspace = true
serde_json.workspace = true
tempfile.workspace = true
zip.workspace = true
sha2.workspace = true
serde_yaml_bw = "2"
greentic-runner-desktop = "0.4"
glob = "0.3"

[features]
schema = ["schemars"]
