[package]
name = "provider-common"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
thiserror.workspace = true
serde_json.workspace = true
schemars = { workspace = true, optional = true }
sha2.workspace = true
ciborium.workspace = true

[dev-dependencies]
anyhow.workspace = true
serde_json.workspace = true
tempfile.workspace = true
zip.workspace = true
sha2.workspace = true
serde_yaml_bw.workspace = true
greentic-runner-desktop.workspace = true
glob.workspace = true
once_cell.workspace = true

[features]
schema = ["schemars"]
